routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PageController@home')->name('home_page');
Auth::routes();

Route::prefix('dashboard')->group(function (){

    // Article Routes
    Route::resource('article', 'Admin\ArticleController');
    Route::get('article/delete/{id}', 'Admin\ArticleController@delete')->name('article.delete');
    Route::get('article/{id}/{title}', 'Admin\ArticleController@show');


    // Poem Routes
    Route::get('/poem/{id}/{title}', 'Admin\PoemController@show');
    Route::resource('poem', 'Admin\PoemController');
    Route::get('poem/delete/{id}', 'Admin\PoemController@delete')->name('poem.delete');



//    Route::get('/artwork/{id}/{title}', 'Admin\ArtworkController@show');
    Route::resource('artwork', 'Admin\ArtworkController');
    Route::get('artwork/delete/{id}', 'Admin\ArtworkController@delete')->name('poem.delete');


    Route::get('/', 'HomeController@index')->name('home');
    Route::prefix('videos')->group(function (){
        Route::get('index', 'HomeController@videos')->name('items.videos');
        Route::any('create', 'HomeController@videos_create')->name('items.videos.create');
        Route::any('edit/{video}', 'HomeController@videos_edit')->name('items.videos.edit');
        Route::any('delete/{video}', 'HomeController@videos_delete')->name('items.videos.delete');
    });

    Route::prefix('pdf')->group(function (){
        Route::get('index', 'PdfController@index')->name('items.document');
        Route::any('create', 'PdfController@create')->name('items.document.create');
        Route::any('edit/{video}', 'PdfController@edit')->name('items.document.edit');
        Route::any('delete/{video}', 'PdfController@delete')->name('items.document.delete');
    });

    Route::prefix('audio')->group(function (){
        Route::get('index', 'HomeController@videos')->name('items.audio');
        Route::any('create', 'HomeController@videos_create')->name('items.audio.create');
        Route::any('edit/{video}', 'HomeController@videos_edit')->name('items.audio.edit');
        Route::any('delete/{video}', 'HomeController@videos_delete')->name('items.audio.delete');
    });


    Route::prefix('advert')->group(function (){
        Route::get('index', 'HomeController@videos')->name('items.advert');
        Route::any('create', 'HomeController@videos_create')->name('items.advert.create');
        Route::any('edit/{video}', 'HomeController@videos_edit')->name('items.advert.edit');
        Route::any('delete/{video}', 'HomeController@videos_delete')->name('items.advert.delete');
    });


});


Route::get('member/signup', 'Auth\RegisterController@showMemberRegisterForm')->name('signup');

Route::post('member/register', 'Auth\RegisterController@createMember')->name('register');

Route::get('member/member_login', 'Auth\MemberLoginController@showMemberLoginForm')->name('member_login');

Route::post('member/login', 'Auth\MemberLoginController@MemberLogin')->name('login_member');



Route::group(['middleware' => ['auth:member']], function () {

// Portal Homepage
	Route::get('member/home', 'Portal\PortalPagesController@member_home')->name('dashboard');

	Route::resource('member/profile', 'Portal\ProfileController', ['names' => [
		'index' => 'member.profile.index',
		'edit' => 'member.profile.edit',
		'update' => 'member.profile.update',
	]]);

	Route::resource('tasks', 'TasksController', ['names' => [
		'index' => 'task.index',
		'edit' => 'task.edit',
		'update' => 'task.update',
	]]);
});

Route::view('forgot_password', 'subscriber..password_reset')->name('member.password_reset');

app/Poem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Poem extends Model
{
    use SoftDeletes;

    protected $fillable = ['title', 'content', 'image'];

    public function poemUrl(){
        return url('dashboard/poem/'.$this->id.'/'.Str::slug($this->title));
    }
}

app/Http/Controllers/Admin/PoemController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\PoemsDataTable;
use App\Http\Controllers\Controller;
use App\Poem;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\Console\Input\Input;

class PoemController extends Controller
{
    public function index()
    {
        $poems = Poem::query()->orderBy('id', 'desc')->get();
        return view('admin.poems.index', compact('poems'));
    }

    public function create()
    {
        return view('admin.poems.create');
    }

    public function store(Request $request)
    {
        $rules = [
            'title' => ['required'],
            'image' => ['required', 'image','mimes:jpeg,png,jpg,gif,svg','max:2048'],
            'content' => ['required'],
        ];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()){
            return back()->withErrors($validator);
        }else{
            $image = $request->file('image');
            $poem_image = time().$image->getClientOriginalName();
            $image->move('images/poem_images', $poem_image);
            DB::beginTransaction();
            Poem::create([
                'title' => $request->title,
                'image' => 'images/poem_images/'.$poem_image,
                'content' => $request->content,
            ]);
            DB::commit();
            Session::flash('success', 'Poem has been saved successfully');
            return back();
        }
    }

    public function show($id)
    {
        $poem = Poem::find($id);
        return view('admin.poems.show', compact('poem'));
    }

    public function edit($id)
    {
        $poem = Poem::find($id);
        return view('admin.poems.edit', compact('poem'));
    }

    public function update(Request $request, $id)
    {
        $poem = Poem::find($id);
        $rules = [
            'title' => ['required'],
            'content' => ['required'],
        ];
        $poem->title = $request->title;
        $poem->content = $request->content;
        $validator = Validator::make($request->all(), $rules);
//        $image = public_path($poem->image);
        if ($request->image) {
            if ($poem->image != null && File::exists( $poem->image)) {
                File::delete($poem->image);
            }

            $image = $request->file('image');
            $poem_image = time().$image->getClientOriginalName();
            $image->move('images/poem_images/', $poem_image);
            $poem->image = 'images/poem_images/'.$poem_image;
//            return $poem->image;
        }
        if ($validator->fails()){
            return back()->withErrors($validator);
        }else{
            DB::beginTransaction();
            $poem->save();
            DB::commit();
            Session::flash('success', 'Poem has been updated successfully');
            return back();
        }
    }

    public function delete($id)
    {
        $poem = Poem::find($id);
        $image = public_path($poem->image);
        if (File::exists($image)) {
            File::delete($image);
        }
        $poem->delete();
        Session::flash('success', 'Poem has been deleted successfully');
        return back();
    }
}

resources/views/admin/poems/create.blade.php
@extends('layouts.app')
@include('admin.header')

@section('content')
    <div class="page-content">
        <!-- Sidebar -->
    @include('layouts.sidebar')
    <!-- Main content -->
        <div class="content-wrapper mt-5">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">CHURCH BLOG</span></h4>
                    <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
                </div>
            </div>
            <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
                <div class="d-flex">
                    <div class="breadcrumb">
                        <a href="{{ route('home')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                        <a href="" class="breadcrumb-item">Add Poem</a>

                    </div>
                </div>
            </div>
            <div class="content">
                <!-- 2 columns form -->
                <div class="card">
                    <div class="card-header header-elements-inline">
                        <h5></h5>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                                <a class="list-icons-item" data-action="reload"></a>
                                <a class="list-icons-item" data-action="remove"></a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                       @include('layouts.session')
                        <form class="row" method="POST" action="{{ route('poem.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group col-md-6">
                                <label>Title:</label>
                                <input name="title" type="text" placeholder="Title" class="form-control"  value="">
                                @error('title')
                                <p class="text-danger">{{ $errors->first('title')}}</p>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label>Post Image:</label>
                                <input name="image" class="form-control" type="file" placeholder=""  value="">
                                @error('image')
                                <p class="text-danger">{{ $errors->first('image')}}</p>
                                @enderror
                            </div>
                            <div class="form-group col-md-12">
                                <textarea class="form-control" id="textbody" name="content" rows="5"></textarea>
                                @error('content')
                                <p class="text-danger">{{ $errors->first('content')}}</p>
                                @enderror
                            </div>
                            <div class="col-md-12 text-center">
                                <button class="btn btn-primary mt-3">Add Poem</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/admin/poems/edit.blade.php
@extends('layouts.app')
@include('admin.header')

@section('content')
    <div class="page-content">
        <!-- Sidebar -->
    @include('layouts.sidebar')
    <!-- Main content -->
        <div class="content-wrapper mt-5">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">CHURCH BLOG</span></h4>
                    <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
                </div>
            </div>
            <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
                <div class="d-flex">
                    <div class="breadcrumb">
                        <a href="{{ route('home')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                        <a href="" class="breadcrumb-item">Add Poem</a>

                    </div>
                </div>
            </div>
            <div class="content">
                <!-- 2 columns form -->
                <div class="card">
                    <div class="card-header header-elements-inline">
                        <h5></h5>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                                <a class="list-icons-item" data-action="reload"></a>
                                <a class="list-icons-item" data-action="remove"></a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        @include('layouts.session')
                        <form class="row" method="POST" action="{{ route('poem.update', $poem->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="form-group col-md-6">
                                <label>Title:</label>
                                <input name="title" type="text" placeholder="Title" class="form-control"  value="{{ old('title') != '' ? old('title') : $poem->title }}">
                                @error('title')
                                <p class="text-danger">{{ $errors->first('title')}}</p>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label>Post Image:</label>
                                <input name="image" class="form-control" type="file" placeholder=""  value="">
                                @error('image')
                                <p class="text-danger">{{ $errors->first('image')}}</p>
                                @enderror
                            </div>
                            <div class="form-group col-md-12">
                                <textarea class="form-control" id="textbody" name="content" rows="5">{{ old('content') != '' ? old('content') : $poem->content}}</textarea>
                                @error('content')
                                <p class="text-danger">{{ $errors->first('content')}}</p>
                                @enderror
                            </div>
                            <div class="col-md-12 text-center">
                                <button class="btn btn-primary mt-3">Update Poem</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/poems/index.blade.php
@extends('layouts.app')
@include('admin.header')

@section('content')
    <div class="page-content">
        <!-- Sidebar -->
    @include('layouts.sidebar')
    <!-- Main content -->
        <div class="content-wrapper mt-5">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">POEMS</span></h4>
                    <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
                </div>
            </div>
            <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
                <div class="d-flex">
                    <div class="breadcrumb">
                        <a href="{{ route('home')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                        <a href="" class="breadcrumb-item">View Poems</a>

                    </div>
                </div>
            </div>
            <div class="content">
                @include('layouts.session')
            <!-- Inner container -->
                <div class="d-flex align-items-start flex-column flex-md-row">
                    @if(count($poems) > 0)
                    @foreach($poems as $poem)
                        <div class="col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card-img-actions mb-3">
                                        <img class="card-img img-fluid" src="{{ asset($poem->image) }}" alt="">
                                        <div class="card-img-actions-overlay card-img">
                                            <a href="" class="btn btn-outline bg-white text-white border-white border-2 btn-icon rounded-round">
                                                <i class="icon-link"></i>
                                            </a>
                                        </div>
                                    </div>

                                    <h5 class="font-weight-semibold mb-1">
                                        <a href="" class="text-default">{{ $poem->title }}</a>
                                    </h5>

                                    <ul class="list-inline list-inline-dotted text-muted mb-3">
                                        <li class="list-inline-item">{{ date('M d, Y', strtotime($poem->created_at)) }}</li>
                                    </ul>
                                    <section>
                                        {!! Str::limit($poem->content, 200) !!}
                                    </section>
                                </div>
                                <br>
                                <div class="card-footer d-flex">
                                    <a href="{{route('poem.edit', $poem->id)}}" class="btn btn-primary mr-2"><span class="fa fa-edit"></span></a>
                                    <a href="{{ route('poem.delete', $poem->id) }}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this poem?')"><span class="fa fa-trash"></span></a>
                                    <a href="{{$poem->poemUrl()}}" class="ml-auto">Read more <i class="icon-arrow-right14 ml-2"></i></a>
                                </div>
                            </div>
                        </div>
                    @endforeach
                    @else
                        <h1>There are no new poems at the moment</h1>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/poems/show.blade.php
@extends('layouts.app')
@include('admin.header')

@section('content')
    <div class="page-content">
    @include('layouts.sidebar')
        <!-- Sidebar -->
        <div class="content-wrapper mt-5">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">POEMS</span></h4>
                    <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
                </div>
            </div>
            <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
                <div class="d-flex">
                    <div class="breadcrumb">
                        <a href="{{ route('home')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                        <a href="{{ route('poem.index') }}" class="breadcrumb-item">Poems</a>
                        <a href="" class="breadcrumb-item">{{$poem->title}}</a>
                    </div>
                </div>
            </div>
            <section class="blogs pt-5 pl-4">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="posts">
                                <div class="post">
                                    <div class="post-img">
                                        <a href="javascript:void(0);" class="width-100 ">
                                            <img src="{{ asset($poem->image) }}" alt="">
                                        </a>
                                    </div>
                                    <div class="content">
                                        <div class="blog-list-simple-text">
                                            <div class="post-title">
                                                <h5 class="mb-3 ml-0">{{$poem->title}}</h5>
                                            </div>
                                            <ul class="meta">
                                                <li>
                                                    <a href="javascript:void(0);">
                                                        <i aria-hidden="true" class="fa fa-calendar-alt"></i> {{ date('l M d, Y', strtotime($poem->created_at)) }}
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:void(0);">
                                                        <i aria-hidden="true" class="fa fa-clock"></i> {{ date('h:iA', strtotime($poem->created_at)) }}
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="post-cont">
                                            {!! $poem->content !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection