routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PageController@home')->name('home_page');
Auth::routes();

Route::prefix('dashboard')->group(function (){

    // Article Routes
    Route::resource('article', 'Admin\ArticleController');
    Route::get('article/delete/{id}', 'Admin\ArticleController@delete')->name('article.delete');
    Route::get('article/{id}/{title}', 'Admin\ArticleController@show');


    // Poem Routes
    Route::get('/poem/{id}/{title}', 'Admin\PoemController@show');
    Route::resource('poem', 'Admin\PoemController');
    Route::get('poem/delete/{id}', 'Admin\PoemController@delete')->name('poem.delete');



//    Route::get('/artwork/{id}/{title}', 'Admin\ArtworkController@show');
    Route::resource('artwork', 'Admin\ArtworkController');
    Route::get('artwork/delete/{id}', 'Admin\ArtworkController@delete')->name('poem.delete');


    Route::get('/', 'HomeController@index')->name('home');
    Route::prefix('videos')->group(function (){
        Route::get('index', 'HomeController@videos')->name('items.videos');
        Route::any('create', 'HomeController@videos_create')->name('items.videos.create');
        Route::any('edit/{video}', 'HomeController@videos_edit')->name('items.videos.edit');
        Route::any('delete/{video}', 'HomeController@videos_delete')->name('items.videos.delete');
    });

    Route::prefix('pdf')->group(function (){
        Route::get('index', 'PdfController@index')->name('items.document');
        Route::any('create', 'PdfController@create')->name('items.document.create');
        Route::any('edit/{video}', 'PdfController@edit')->name('items.document.edit');
        Route::any('delete/{video}', 'PdfController@delete')->name('items.document.delete');
    });

    Route::prefix('audio')->group(function (){
        Route::get('index', 'HomeController@videos')->name('items.audio');
        Route::any('create', 'HomeController@videos_create')->name('items.audio.create');
        Route::any('edit/{video}', 'HomeController@videos_edit')->name('items.audio.edit');
        Route::any('delete/{video}', 'HomeController@videos_delete')->name('items.audio.delete');
    });


    Route::prefix('advert')->group(function (){
        Route::get('index', 'HomeController@videos')->name('items.advert');
        Route::any('create', 'HomeController@videos_create')->name('items.advert.create');
        Route::any('edit/{video}', 'HomeController@videos_edit')->name('items.advert.edit');
        Route::any('delete/{video}', 'HomeController@videos_delete')->name('items.advert.delete');
    });


});


Route::get('member/signup', 'Auth\RegisterController@showMemberRegisterForm')->name('signup');

Route::post('member/register', 'Auth\RegisterController@createMember')->name('register');

Route::get('member/member_login', 'Auth\MemberLoginController@showMemberLoginForm')->name('member_login');

Route::post('member/login', 'Auth\MemberLoginController@MemberLogin')->name('login_member');



Route::group(['middleware' => ['auth:member']], function () {

// Portal Homepage
	Route::get('member/home', 'Portal\PortalPagesController@member_home')->name('dashboard');

	Route::resource('member/profile', 'Portal\ProfileController', ['names' => [
		'index' => 'member.profile.index',
		'edit' => 'member.profile.edit',
		'update' => 'member.profile.update',
	]]);

	Route::resource('tasks', 'TasksController', ['names' => [
		'index' => 'task.index',
		'edit' => 'task.edit',
		'update' => 'task.update',
	]]);
});

Route::view('forgot_password', 'subscriber..password_reset')->name('member.password_reset');

app/Artwork.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Artwork extends Model
{
    protected $fillable = ['image', 'file'];
}

app/Http/Controllers/Admin/ArtworkController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Artwork;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ArtworkController extends Controller
{
    public function index()
    {
        return view('admin.artworks.index');
    }

    public function create()
    {
        return view('admin.artworks.create');
    }

    public function store(Request $request)
    {
        $artwork = new Artwork();
        $rules = [
            'image' => ['required', 'mimes: pdf', 'max: 5000'],
            'file' => ['required', 'image','mimes:jpeg,png,jpg,gif,svg','max:2048'],
        ];
        $validator = Validator::make($request->all(),$rules);
        if ($validator->fails()){
            return back()->withErrors($validator);
        }


    }

    public function show()
    {

    }

    public function edit()
    {

    }

    public function update()
    {

    }

    public function delete()
    {

    }
}

resources/views/admin/artworks/create.blade.php
@extends('layouts.app')
@include('admin.header')

@section('content')
    <div class="page-content">
        <!-- Sidebar -->
    @include('layouts.sidebar')
    <!-- Main content -->
        <div class="content-wrapper mt-5">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">ARTWORK</span></h4>
                    <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
                </div>
            </div>
            <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
                <div class="d-flex">
                    <div class="breadcrumb">
                        <a href="{{ route('home')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                        <a href="" class="breadcrumb-item">Add Artwork</a>

                    </div>
                </div>
            </div>
            <div class="content">
                <!-- 2 columns form -->
                <div class="card">
                    <div class="card-header header-elements-inline">
                        <h5></h5>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                                <a class="list-icons-item" data-action="reload"></a>
                                <a class="list-icons-item" data-action="remove"></a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        @include('layouts.session')
                        <form class="row" method="POST" action="{{ route('artwork.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group col-md-6">
                                <label>Title:</label>
                                <input name="file" type="file"  class="form-control"  value="">
                                @error('file')
                                <p class="text-danger">{{ $errors->first('file')}}</p>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label>Artwork Thumbnail:</label>
                                <input name="image" class="form-control" type="file" placeholder=""  value="">
                                @error('image')
                                <p class="text-danger">{{ $errors->first('image')}}</p>
                                @enderror
                            </div>
                            <div class="col-md-12 text-center">
                                <button class="btn btn-primary mt-3">Add Artwork</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection