routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PageController@home')->name('home_page');
Auth::routes();

Route::prefix('dashboard')->group(function (){

    // Article Routes
    Route::resource('article', 'Admin\ArticleController');
    Route::get('article/delete/{id}', 'Admin\ArticleController@delete')->name('article.delete');
    Route::get('article/{id}/{title}', 'Admin\ArticleController@show');


    // Poem Routes
    Route::get('/poem/{id}/{title}', 'Admin\PoemController@show');
    Route::resource('poem', 'Admin\PoemController');
    Route::get('poem/delete/{id}', 'Admin\PoemController@delete')->name('poem.delete');



//    Route::get('/artwork/{id}/{title}', 'Admin\ArtworkController@show');
    Route::resource('artwork', 'Admin\ArtworkController');
    Route::get('artwork/delete/{id}', 'Admin\ArtworkController@delete')->name('poem.delete');


    Route::get('/', 'HomeController@index')->name('home');
    Route::prefix('videos')->group(function (){
        Route::get('index', 'HomeController@videos')->name('items.videos');
        Route::any('create', 'HomeController@videos_create')->name('items.videos.create');
        Route::any('edit/{video}', 'HomeController@videos_edit')->name('items.videos.edit');
        Route::any('delete/{video}', 'HomeController@videos_delete')->name('items.videos.delete');
    });

    Route::prefix('pdf')->group(function (){
        Route::get('index', 'PdfController@index')->name('items.document');
        Route::any('create', 'PdfController@create')->name('items.document.create');
        Route::any('edit/{video}', 'PdfController@edit')->name('items.document.edit');
        Route::any('delete/{video}', 'PdfController@delete')->name('items.document.delete');
    });

    Route::prefix('audio')->group(function (){
        Route::get('index', 'HomeController@videos')->name('items.audio');
        Route::any('create', 'HomeController@videos_create')->name('items.audio.create');
        Route::any('edit/{video}', 'HomeController@videos_edit')->name('items.audio.edit');
        Route::any('delete/{video}', 'HomeController@videos_delete')->name('items.audio.delete');
    });


    Route::prefix('advert')->group(function (){
        Route::get('index', 'HomeController@videos')->name('items.advert');
        Route::any('create', 'HomeController@videos_create')->name('items.advert.create');
        Route::any('edit/{video}', 'HomeController@videos_edit')->name('items.advert.edit');
        Route::any('delete/{video}', 'HomeController@videos_delete')->name('items.advert.delete');
    });


});


Route::get('member/signup', 'Auth\RegisterController@showMemberRegisterForm')->name('signup');

Route::post('member/register', 'Auth\RegisterController@createMember')->name('register');

Route::get('member/member_login', 'Auth\MemberLoginController@showMemberLoginForm')->name('member_login');

Route::post('member/login', 'Auth\MemberLoginController@MemberLogin')->name('login_member');



Route::group(['middleware' => ['auth:member']], function () {

// Portal Homepage
	Route::get('member/home', 'Portal\PortalPagesController@member_home')->name('dashboard');

	Route::resource('member/profile', 'Portal\ProfileController', ['names' => [
		'index' => 'member.profile.index',
		'edit' => 'member.profile.edit',
		'update' => 'member.profile.update',
	]]);

	Route::resource('tasks', 'TasksController', ['names' => [
		'index' => 'task.index',
		'edit' => 'task.edit',
		'update' => 'task.update',
	]]);
});

Route::view('forgot_password', 'subscriber..password_reset')->name('member.password_reset');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Zedek</title>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    {{--  DATATABLE CSS --}}
     <link href="{{asset('css/datatable/dataTables.bootstrap4.css')}}" rel="stylesheet">
    <link href="{{asset('css/datatable/jquery.dataTables.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/datatable/buttons.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/datatable/buttons.dataTables.min.css')}}" rel="stylesheet">



    <!-- DATATABLE JS -->


    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="{{ asset('global_assets/css/icons/icomoon/styles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('global_assets/css/admin-custom.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/bootstrap_limitless.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/layout.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/components.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/colors.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('website/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{{ asset('website/css/custom.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('global_assets/css/summernote.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('global_assets/css/tagsinput.css') }}">
    <script src="{{asset('js/ckeditor/ckeditor.js')}}"></script>
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script src="{{ asset('global_assets/js/main/jquery.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/main/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/loaders/blockui.min.js') }}"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script src="{{ asset('global_assets/js/plugins/visualization/d3/d3.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/styling/switchery.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/styling/switchery.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/selects/bootstrap_multiselect.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/ui/moment/moment.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/pickers/daterangepicker.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/ui/perfect_scrollbar.min.js') }}"></script>
    <script src="{{ asset('website/js/all.min.js') }}"></script>

    <!-- Theme JS files -->
    <script src="{{ asset('global_assets/js/plugins/visualization/echarts/echarts.min.js') }}"></script>

    <!-- Theme JS files -->
  {{--   <script src="{{ asset('global_assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/tables/datatables/extensions/responsive.min.js') }}"></script> --}}
    <script src="{{ asset('global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <!-- Theme JS files -->
    <script src="{{ asset('global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset('assets/js/app.js') }}"></script>
    <script src="{{ asset('global_assets/js/demo_pages/dashboard.js') }}"></script>
    <script src="{{ asset('global_assets/js/demo_pages/layout_fixed_sidebar_custom.js') }}"></script>
    <script src="{{ asset('global_assets/js/demo_pages/charts/echarts/bars_tornados.js') }}"></script>
    <script src="{{ asset('global_assets/js/demo_pages/charts/echarts/pies_donuts.js') }}"></script>
    <script src="{{ asset('global_assets/js/demo_pages/form_layouts.js') }}"></script>
    <script type="text/javascript" src="{{ asset('global_assets/js/summernote.min.js') }}"></script>
    <script src="{{ asset('global_assets/js/demo_pages/widgets_content.js') }}"></script>
    <script type="text/javascript" src="{{ asset('global_assets/js/tagsinput.js') }}"></script>
    <!-- /theme JS files -->
</head>
<body>
    <div id="app">
        <!-- Main navbar -->
    <!-- /main navbar -->
        <main class="mb-0">
            @yield('content')
        </main>
    </div>
      <script src="{{asset('js/datatable/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('js/datatable/dataTables.bootstrap4.js')}}"></script>
    <script src="{{asset('js/datatable/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('js/datatable/buttons.print.min.js')}}"></script>
    <script src="{{asset('js/datatable/buttons.server-side.js')}}"></script>
    @stack('tables')
    @stack('script')
    <script>
        $('#basic-datatables').DataTable({
        });
        CKEDITOR.replace('textbody');
        // CKEDITOR.replace('editbody');
        CKEDITOR.config.height ='300px';
    </script>
<script src="{{ asset('js/main.js') }}"></script>
</body>
</html>

resources/views/layouts/footer.blade.php
<div class="navbar navbar-expand-lg navbar-light">
                <div class="text-center d-lg-none w-100">
                    <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
                        <i class="icon-unfold mr-2"></i>
                        Footer
                    </button>
                </div>

                <div class="navbar-collapse collapse" id="navbar-footer">
                    <span class="navbar-text" style="text-align: center">
                        &copy; Copyright 2020. All Rights Reserved.
                    </span>
                </div>
            </div>
            <!-- /footer -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</body>
</html>        <!-- /footer -->
    </div>
    <!-- /main content -->
</div>
<!-- /page content -->
</div>
<script>
    $("#phone").keydown((e)=>{
        if(e.which > 64 && e.which < 91)
        {
        e.preventDefault();
        alert("Enter a Valid Phone Number");
        }
        });
    $('#phone').on('blur', function(e) {
        const regex = /^\D*(\d{3})\D*(\d{3})\D*(\d{4})\D*$/g;
        const number =  $(this).val().replace(regex,  '($1) $2-$3');
        $('#phone').val(number);
     });
     
</script>

resources/views/layouts/session.blade.php
@if(Session::has('success'))
    <p class="alert alert-success">{{Session('success')}}</p>
@endif
@if(Session::has('fail'))
    <p class="alert alert-danger">{{Session('fail')}}</p>
    @endif

resources/views/layouts/sidebar.blade.php
<!-- Main sidebar -->
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md" >

    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        Navigation
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>


    <!-- Sidebar content -->
    <div class="sidebar-content mt-5">
        <!-- User menu -->
        <div class="sidebar-user pt-5">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3">
                        @if (Auth::user()->avatar)
                        <img src="{{ URL::to('/') }}/ProfileImg/{{ Auth::user()->avatar }}" alt="Avatar" width="50" height="50" class="rounded-circle mt-5">
                        @else
                        <img src="{{ asset('/images/img/user.png') }}" alt="Avatar"  width="50" height="50" class="rounded-circle mt-5">
                        @endif
                    </div>

                    <div class="media-body">
                        <div class="media-title font-weight-semibold">{{ Auth::user()->name }}</div>
                        <div class="media-title font-weight-semibold">{{ Auth::user()->email }}</div>
                    </div>




                    <div class="ml-3 align-self-center">
                        <a href="#" class="text-white"><i class="icon-cog3"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /user menu -->


        <!-- Main navigation -->
        <div class="card card-sidebar-mobile">
            <ul class="nav nav-sidebar" data-nav-type="accordion">

                <!-- Main -->
                <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
                <li class="nav-item">
                    <a href="{{ route('home')}}" class="nav-link {{ Request::path() === 'dashboard' ? 'active' : ''}}">
                        <i class="icon-home4"></i>
                        <span>
                            Home
                        </span>
                    </a>
                </li>
                <li class="nav-item nav-item-submenu">
                    <a href="" class="nav-link"><i class="fab fa-opencart mr-3" style="font-size: 18px;"></i> <span>Poems</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                        <li class="nav-item"><a href="{{route('poem.create')}}" class="nav-link active">Add Poem</a></li>
                        <li class="nav-item"><a href="{{ route('poem.index') }}" class="nav-link active">View Poems</a></li>

                    </ul>
                </li>

                <li class="nav-item nav-item-submenu">
                    <a href="" class="nav-link"><i class="fab fa-opencart mr-3" style="font-size: 18px;"></i> <span>Articles</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                        <li class="nav-item"><a href="{{route('article.create')}}" class="nav-link active">Add Articles</a></li>
                        <li class="nav-item"><a href="{{ route('article.index') }}" class="nav-link active">View Articles</a></li>
                    </ul>
                </li>

                <li class="nav-item nav-item-submenu">
                    <a href="" class="nav-link"><i class="fab fa-opencart mr-3" style="font-size: 18px;"></i> <span>Artwork</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                        <li class="nav-item"><a href="{{route('artwork.create')}}" class="nav-link active">Add Artwork</a></li>
                        <li class="nav-item"><a href="{{ route('artwork.index') }}" class="nav-link active">View Artworks</a></li>
                    </ul>
                </li>



                <li class="nav-item">
                    <a href="{{ route('items.videos')}}" class="nav-link {{ Request::path() === 'dashboard/videos/index' ? 'active' : ''}}">
                        <i class="icon-home4"></i>
                        <span>Videos</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('items.document')}}" class="nav-link {{ Request::path() === 'dashboard/document/index' ? 'active' : ''}}">
                        <i class="icon-home4"></i>
                        <span>Audio</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('items.document')}}" class="nav-link {{ Request::path() === 'dashboard/videos/index' ? 'active' : ''}}">
                        <i class="icon-home4"></i>
                        <span>Document/PDF</span>
                    </a>
                </li>

                <li class="nav-item nav-item-submenu">
                    <a href="#" class="nav-link {{ Request::path() === 'staff' ? 'active' : ''}}"><i class="icon-users"></i> <span>Users</span></a>

                    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                        <li class="nav-item"><a href="#" class="nav-link active">List of Users</a></li>
                    </ul>
                </li>

                <li class="nav-item nav-item-submenu">
                    <a href="#" class="nav-link {{ Request::path() === 'sermons' ? 'active' : ''}}"><i class="fab fa-teamspeak mr-3" style="font-size: 18px;"></i> <span>Sermon</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                        <li class="nav-item"><a href="" class="nav-link active">Upload Sermon</a></li>
                    </ul>
                </li>









                <!-- /main -->
                <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Online Store</div> <i class="icon-menu" title="Forms"></i></li>
                <li class="nav-item">
                    <a href="" class="nav-link {{ Request::path() === 'product_categories' ? 'active' : ''}}">
                        <i class="fas fa-shopping-cart mr-3" style="font-size: 18px;"></i>
                        <span>
                            Resource Categories
                        </span>
                    </a>
                </li>
                <li class="nav-item nav-item-submenu">
                    <a href="" class="nav-link"><i class="fab fa-opencart mr-3" style="font-size: 18px;"></i> <span>Resources</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                        <li class="nav-item"><a href="" class="nav-link active">Add Resource</a></li>
                        <li class="nav-item"><a href="{" class="nav-link active">View Resources</a></li>

                    </ul>
                </li>








                <li class="nav-item nav-item-submenu">
                    <a href="" class="nav-link"><i class="fa fa-newspaper mr-3" style="font-size: 18px;"></i> <span>Blog</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                        <li class="nav-item"><a href="" class="nav-link active">Add Blog Post</a></li>
                        <li class="nav-item"><a href="" class="nav-link active">View Blog Posts</a></li>

                    </ul>
                </li>


                <!-- /page kits -->
                <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Extras</div> <i class="icon-menu" title="Forms"></i></li>
                <li class="nav-item">
                    <a href="" class="nav-link"><i class="fa fa-box mr-3" style="font-size: 18px;"></i> <span>Activity Log</span></a>
                </li>
                <!-- /page kits -->

            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->

</div>
<!-- /main sidebar -->